
Search

version: 2

models:

    name: FACT_SALES columns:

        name: sales_id tests:
            not_null
            unique

        name: order_id tests:
            not_null
            unique

        name: customer_id tests:
            not_null
            relationships: to: ref('DIM_CUSTOMER') field: customer_id

        name: product_id tests:
            not_null
            relationships: to: ref('DIM_PRODUCT') field: product_id

        name: order_status tests:
            not_null
            accepted_values: values: ['pending', 'completed', 'canceled', 'returned']

    name: DIM_CUSTOMER columns:
        name: customer_id tests:
            not_null
            unique

    name: DIM_PRODUCT columns:
        name: product_id tests:
            not_null
            unique

;
Table of contents
Notebook is not connected to service
	
	
