USE database olist_db; 
create schema STAGING;
CREATE OR REPLACE VIEW STAGING.STG_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM RAW.RAW_CUSTOMER;

CREATE OR REPLACE VIEW STAGING.STG_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,


USE DATABASE olist_db;
    CREATE OR REPLACE VIEW STAGING.STG_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM STG.RAW_CUSTOMER;

    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE
FROM RAW.RAW_ORDERS;

CREATE OR REPLACE VIEW STAGING.STG_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT,
    PRODUCT_DESCRIPTION_LENGHT,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
FROM RAW.RAW_PRODUCT;

CREATE OR REPLACE VIEW STAGING.STG_ORDER_ITEMS AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE
FROM RAW.RAW_ORDER_ITEM;

CREATE OR REPLACE VIEW STAGING.STG_PAYMENTS AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM RAW.RAW_PAYMENT;


USE database olist_db;
use schema mart;
use schema staging;
CREATE OR REPLACE VIEW STAGING.STG_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_UNIQUE_ID,
    CUSTOMER_ZIP_CODE_PREFIX,
    CUSTOMER_CITY,
    CUSTOMER_STATE
FROM RAW.RAW_CUSTOMER;
CREATE OR REPLACE VIEW MART.DIM_CUSTOMERS AS
SELECT *
FROM STAGING.STG_CUSTOMERS;


CREATE OR REPLACE VIEW STAGING.STG_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_STATUS,
    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE
FROM RAW.RAW_ORDERS;

CREATE OR REPLACE VIEW STAGING.STG_PRODUCTS AS
SELECT
    PRODUCT_ID,
    PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT,
    PRODUCT_DESCRIPTION_LENGHT,
    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM
FROM RAW.RAW_PRODUCT;
CREATE OR REPLACE VIEW STAGING.STG_ORDER_ITEMS AS
SELECT
    ORDER_ID,
    ORDER_ITEM_ID,
    PRODUCT_ID,
    SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    FREIGHT_VALUE
FROM RAW.RAW_ORDER_ITEM;
CREATE OR REPLACE VIEW STAGING.STG_PAYMENTS AS
SELECT
    ORDER_ID,
    PAYMENT_SEQUENTIAL,
    PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE
FROM RAW.RAW_PAYMENT;

CREATE OR REPLACE VIEW MARTS.DIM_CUSTOMERS AS
SELECT *
FROM STAGING.STG_CUSTOMERS;

CREATE OR REPLACE VIEW MART.DIM_PRODUCTS AS
SELECT *
FROM STAGING.STG_PRODUCTS;

CREATE OR REPLACE VIEW MART.FACT_SALES_1 AS
SELECT
    o.ORDER_ID,
    c.CUSTOMER_ID,
    p.PRODUCT_ID,
    o.ORDER_PURCHASE_TIMESTAMP AS ORDER_DATE,
    o.ORDER_STATUS,
    oi.PRICE,
    oi.FREIGHT_VALUE,
    pay.PAYMENT_VALUE,
    pay.PAYMENT_TYPE
FROM STAGING.STG_ORDERS o
LEFT JOIN STAGING.STG_ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
LEFT JOIN STAGING.STG_PAYMENTS pay ON o.ORDER_ID = pay.ORDER_ID
LEFT JOIN MART.DIM_CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN MART.DIM_PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID;




